server:
    port: 8082
    servlet:
      context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
      
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: android
#      clientSecret: android
#      accessTokenUri: http://127.0.0.1:8763/oauth/access_token
#      userAuthorizationUri: http://127.0.0.1:8763/oauth/authorize
#    resource:
#      userInfoUri: http://127.0.0.1:8763/user
spring:
  thymeleaf:
    cache: false        