server:
    port: 7073
    servlet:
      context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
      
zuul:
  ignored-services: '*'
  routes:
    auth-server:
      path: /uaa/**
      serviceId: secu-oauth
      sensitiveHeaders:
      strip-prefix: false
    api-account: 
      path: /api-account/**
      service-id: account-service
    api-a: 
      path: /api-a/**
      service-id: service-A
    api-b: 
      path: /api-b/**
      service-id: service-B
logging:
  config: classpath:logback.xml
spring:
  thymeleaf:
    cache: false        